# Generated by Django 2.2 on 2020-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmition',
            fields=[
                ('am_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=12)),
                ('wclass', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('fees', models.IntegerField(max_length=70)),
                ('pfees', models.IntegerField(max_length=70)),
                ('dob', models.DateField(max_length=70)),
            ],
        ),
    ]
