# Generated by Django 2.2 on 2020-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmition',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addmition',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addmition',
            name='pfees',
            field=models.IntegerField(),
        ),
    ]
