# Generated by Django 2.2 on 2020-03-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200320_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmition',
            old_name='pfees',
            new_name='pending_fees',
        ),
    ]
